### ISSUE TITLE
Unable to use my own profile picture.

### ISSUE THREAD

**Issue by francois-de-mareschal** [suheb/resume#2]
First, thank you for the awesome work, it saves me a lot of time!

Nevertheless, I am encountering a weird issue: I cannot use my own profile picture. To use this custom picture, I did these steps:
* I dropped an image in the repository root
* I set the `PIC` constant in the `pelicanconf.py` file

I can see the right path in the generated HTML file to be sent to the server, but the file is never moved or copied to the place where it should, i.e. the `/themes/images` directory.

Perhaps I missed something?

**Comment by francois-de-mareschal** [comment]
@suheb up ? :sweat_smile:

**Comment by suheb** [comment]
@fanf22 Currently, the only option is to replace/add the image file in the theme (`theme/images/`) folder.
But I'm working on making this configurable.
